##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: ecomerce
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
  data:
    mongodb:
      uri:
        mongodb://root:root@localhost:27017/IAS
